### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by syamsoul** [maxcal/pagescript#1]
cannot install this gem for rails 5.1.3

**Comment by maxcal** [comment]
This is probably due to that the Gemspec lists the dependency as `'rails', '~> 5.0.0', '>= 5.0.0.1'`. I'll se if I can relax the version requirement and release a new version of the gem today.

**Comment by maxcal** [comment]
You should be able to install the gem now. Just make sure you use `gem 'pagescript', '~> 0.3.0'` to get the latest version.
